"""Render the supplied replacement PDF's questions and a worked, unofficial answer key."""
from html import escape
from pathlib import Path
import shutil
import json
import subprocess
import os
import pymupdf
from build import ROOT, layout

SOURCE = Path('C:/Users/debas/AppData/Local/hermes/cache/documents/doc_e94b91d8d43a_2026_Class_12_Physics_English_Question_Paper_FIXED.pdf')
PAPER = ROOT / 'physics-paper-2026.pdf'
assert SOURCE.is_file()
assert len(pymupdf.open(SOURCE)) == 8
shutil.copyfile(SOURCE, PAPER)

KATEX_DIST = ROOT.parent / 'asseb-half-yearly-study-plan-2026' / 'node_modules' / 'katex' / 'dist'
assert (KATEX_DIST/'katex.min.css').is_file(), 'Run npm ci in the original Physics repo first'
shutil.copyfile(KATEX_DIST/'katex.min.css', ROOT/'physics'/'katex.min.css')
RENDERED_MATH = json.loads(subprocess.run(
    ['node','render_paper_math.js'], cwd=ROOT, check=True, capture_output=True, text=True,
    encoding='utf8', env=os.environ.copy()
).stdout)

def math_for(qid):
    return ''.join('<div class="math-row">'+equation+'</div>' for equation in RENDERED_MATH.get(qid,[]))

Q1 = [
 ('a','The SI unit of electric potential is — (i) Volt (ii) Coulomb (iii) Joule (iv) Newton.','(i) Volt. Potential is work per unit charge: 1 V = 1 J/C.','1'),
 ('b','The work done in moving a charge between two points on the same equipotential surface is — (i) Positive (ii) Negative (iii) Zero (iv) Infinite.','(iii) Zero. ΔV = 0, so W = qΔV = 0.','1'),
 ('c','The SI unit of resistivity is — (i) Ω m (ii) Ω/m (iii) Ω m² (iv) Ω² m.','(i) Ω m. From R = ρL/A, ρ = RA/L.','2'),
 ('d','The magnetic field at the centre of a circular current-carrying coil is directed along its — (i) Radius (ii) Diameter (iii) Axis (iv) Circumference.','(iii) Axis, perpendicular to the plane of the coil; direction follows the right-hand rule.','2'),
 ('e','The magnetic susceptibility of a diamagnetic substance is — (i) Positive (ii) Negative (iii) Zero (iv) Infinite.','(ii) Negative: its induced magnetisation opposes the applied field.','2'),
 ('f',"According to Faraday’s law, induced emf is produced due to a change in — (i) Electric field (ii) Current (iii) Magnetic flux (iv) Resistance.",'(iii) Magnetic flux linked with the circuit; ε = −dΦ/dt for one turn.','2'),
]
Q2 = [
 ('a','Using Gauss’s law, explain why the field inside a hollow conducting sphere is zero.',"In electrostatic equilibrium with no charges in the hollow cavity, excess charge resides on the outer surface and the field within the conducting material is zero. Inside the empty cavity, a concentric Gaussian surface encloses zero charge; spherical symmetry of the isolated charged sphere then gives E(4πr²) = 0, so E = 0. Gauss’s law alone, without symmetry/electrostatic assumptions, establishes zero net flux, not pointwise zero field.",'2–3'),
 ('b','Define electric dipole moment. Write its SI unit.','For charges −q and +q separated by displacement vector d directed from −q to +q, electric dipole moment p = qd. Its SI unit is coulomb metre (C m).','3'),
 ('c','Define current density. Write its SI unit.','Current density J is current per unit area perpendicular to the flow, J = I/A for uniform flow; in general dI/dA. It points along conventional current. SI unit: A m⁻².','3'),
 ('d','A wire carries 5 A. Its cross-sectional area is 2 × 10⁻⁶ m². Calculate the current density.','J = I/A = 5/(2 × 10⁻⁶) = 2.5 × 10⁶ A m⁻².','3'),
 ('e','Write any two properties of magnetic field lines.','They form closed continuous loops (outside a bar magnet they run N to S and inside S to N). They never intersect: otherwise the field would have two directions at one point.','3'),
 ('f','State Ampere’s circuital law and mention one application.','∮ B·dl = μ₀ I<sub>enclosed</sub> for steady currents in vacuum. It is used to find the field around an infinitely long straight current-carrying wire: B = μ₀I/(2πr).','3'),
 ('g','Write Coulomb’s law in vector form. What is the SI unit of permittivity of free space?',"For displacement vector r₂₁ from charge q₁ to q₂: F₂₁ = [q₁q₂/(4πε₀r₂₁²)] r̂₂₁. SI unit of ε₀: F m⁻¹ (equivalently C² N⁻¹ m⁻²). Signs of charges determine force direction.",'3'),
 ('h','State Faraday’s first law of electromagnetic induction.','Whenever magnetic flux linked with a closed circuit changes, an emf is induced; a current flows if the circuit is closed.','3'),
 ('i','What is self-induction?','A changing current in a circuit changes its own magnetic flux and induces an emf opposing that change: ε = −L dI/dt (for constant self-inductance L).','3'),
]
Q3 = [
 ('a','State Gauss’s theorem. Hence obtain the field due to an infinitely long straight line charge.',"Gauss: ∮ E·dA = Q<sub>enc</sub>/ε₀. For uniform line charge density λ, choose a coaxial cylindrical Gaussian surface of radius r and length ℓ. Flux through end faces is zero because E is radial; curved-face flux is E(2πrℓ). Enclosed charge is λℓ. Hence E = λ/(2πε₀r), radially outward for λ&gt;0 (inward for λ&lt;0).",'4',('A charge of 5 μC is at the centre of a cube of side 20 cm. Find flux through each face.',"Total flux through the cube = q/ε₀. By symmetry its six faces receive equal flux: Φ<sub>face</sub> = q/(6ε₀) = 5 × 10⁻⁶/(6 × 8.854 × 10⁻¹²) ≈ 9.41 × 10⁴ N m²/C per face. Side length does not affect the flux.")),
 ('b','Write the law applied in the Wheatstone bridge principle. Draw a Wheatstone bridge.',"The bridge uses Kirchhoff’s circuit laws. At balance the galvanometer current is zero (I<sub>G</sub> = 0). With the arms P = AB, Q = AD, R = BC, S = DC as labelled here, their ratios are P/Q = R/S. Draw the four resistive arms, the galvanometer between B and D, and the source across A and C.",'4',('Derive the relation between current density and drift velocity.',"For charge carriers of number density n, charge q each, and drift velocity vector v<sub>d</sub>, the magnitude of charge crossing area A in Δt is n|q|A|v<sub>d</sub>|Δt. Thus I = n|q|A|v<sub>d</sub>| in magnitude, while the vector current density is J = nqv<sub>d</sub>. For electrons q = −e and electron drift velocity v<sub>d</sub>, the signed vector relation is J = −ne v<sub>d</sub>. Conventional current is opposite their drift. Magnitude: J = ne|v<sub>d</sub>|.")),
 ('c','Using Biot–Savart law, find the field at the centre of a circular current-carrying loop.',"At the centre of a loop of radius R, each current element dl is perpendicular to its radius vector. Biot–Savart: dB = μ₀I dl/(4πR²), all contributions point along the axis. Integrate around the loop: ∮dl = 2πR. Therefore B = μ₀I/(2R) (or μ₀NI/(2R) for N turns).",'4–5',('A circular coil of radius 10 cm carries 5 A. Find its field at the centre.',"Assuming one turn (the paper gives no turn count): R = 0.10 m. B = μ₀I/(2R) = (4π × 10⁻⁷ × 5)/(0.20) = π × 10⁻⁵ T ≈ 3.14 × 10⁻⁵ T. For N turns, multiply by N.")),
 ('d','Differentiate diamagnetic and paramagnetic substances; give an example of each.',"Diamagnetic: χ<sub>m</sub> &lt; 0, weakly repelled; example bismuth. Paramagnetic: χ<sub>m</sub> &gt; 0, weakly attracted; example aluminium. Both responses are weak compared with ferromagnetism.",'5',('Define magnetic susceptibility and establish μ<sub>r</sub> = 1 + χ<sub>m</sub>.',"Magnetic susceptibility is χ<sub>m</sub> = M/H. In a linear isotropic material B = μ₀(H + M) = μ₀(1 + χ<sub>m</sub>)H. By definition B = μ₀μ<sub>r</sub>H; compare coefficients: μ<sub>r</sub> = 1 + χ<sub>m</sub>.")),
 ('e','State Faraday’s laws. A 250-turn coil has flux per turn changing from 0.08 Wb to 0.02 Wb in 0.02 s; calculate the emf.',"First law: a changing flux linkage induces an emf. Second law: ε = −N ΔΦ/Δt (negative sign gives direction). Magnitude |ε| = 250|0.02 − 0.08|/0.02 = 750 V. This treats stated flux as flux per turn; if it meant total flux linkage, the answer would differ.",'5',('State Lenz’s law and explain its consistency with energy conservation.',"The induced current flows in a direction whose magnetic field opposes the change of flux causing it. For example, approaching a magnet induces a field repelling it: external work must be done; that energy becomes electrical/thermal energy. If the induced current aided the approach, energy would appear without work.")),
 ('f','Define self-inductance and obtain the energy stored in an inductor.',"Flux linkage is NΦ = LI; L is self-inductance (unit henry, H). The opposing emf is ε = −L dI/dt. External power to build current is P = I L dI/dt, so dU = LI dI and U = ∫₀ᴵ LI dI = ½LI² (constant L).",'5',('A 4 H coil carries 3 A. Find energy in its magnetic field.','U = ½LI² = ½ × 4 × 3² = 18 J.')),
]
Q4 = [
 ('a','Use Gauss’s law to find the field of a uniformly charged thin spherical shell at external and internal points. Sketch E versus r.',"For total charge Q on a shell of radius R, spherical symmetry gives E(4πr²) = Q<sub>enc</sub>/ε₀. Outside (r &gt; R): Q<sub>enc</sub> = Q, so E = Q/(4πε₀r²). Inside (r &lt; R): Q<sub>enc</sub> = 0, so E = 0. For Q &gt; 0 the field is radial outward. The ideal zero-thickness shell has a discontinuity: E(R⁻) = 0 and E(R⁺) = Q/(4πε₀R²); then it falls as 1/r². The surface itself is not assigned a unique value in the sketch.",'6',('A 12 V battery with 1 Ω internal resistance is connected to an external 5 Ω resistor. Calculate current and terminal voltage.','I = ε/(R + r) = 12/(5 + 1) = 2 A. Terminal potential difference V = ε − Ir = 12 − 2 × 1 = 10 V (also IR = 2 × 5 = 10 V).')),
 ('b','State Faraday’s laws. Explain Lenz’s law and its consistency with energy conservation.',"Faraday’s first law: changing magnetic flux linkage induces an emf (and a current in a closed circuit). Second law: ε = −N dΦ/dt; magnitude is the rate of change of flux linkage. Lenz’s law determines the direction: the induced current opposes the flux change. For a magnet pushed toward a conducting coil, the induced magnetic field resists the approach; the external work supplies the electrical energy and losses. An induced field assisting the motion would violate energy conservation.",'7',('A 500-turn rectangular coil of area 4 × 10⁻³ m² rotates at 120 rad s⁻¹ in a 0.5 T field. Derive ε(t) and maximum emf.',"With normal making angle θ = ωt with the field, Φ = BA cos(ωt) per turn. ε(t) = −N dΦ/dt = NBAω sin(ωt), sign depending on chosen orientation. ε<sub>max</sub> = NBAω = 500 × 0.5 × (4 × 10⁻³) × 120 = 120 V.")),
 ('c','Four 10 μF capacitors form a rectangle: C₁ on left, C₂ on top, C₃ on right, C₄ between the lower nodes. A 500 V supply is across the two lower nodes. Find equivalent capacitance and each charge.',"The top path C₁–C₂–C₃ is a series chain: 1/C<sub>top</sub> = 1/10 + 1/10 + 1/10 = 3/10 (μF)⁻¹, hence C<sub>top</sub> = 10/3 μF. C₄ = 10 μF lies directly across the lower terminals, parallel with that chain. C<sub>eq</sub> = 10 + 10/3 = 40/3 μF ≈ 13.33 μF. Both branches have 500 V. In the series branch each has the same charge: Q₁ = Q₂ = Q₃ = C<sub>top</sub>V = (10/3) × 500 = 5000/3 μC ≈ 1,667 μC. Each of these three drops 500/3 ≈ 166.7 V. Q₄ = C₄V = 10 × 500 = 5,000 μC. Total supplied charge = (40/3) × 500 = 20,000/3 μC ≈ 6,667 μC.",'7–8',('R₁ is in series with R₂ and R₃ in parallel. Show I = V(R₂ + R₃)/(R₁R₂ + R₁R₃ + R₂R₃).',"R<sub>parallel</sub> = R₂R₃/(R₂ + R₃). R<sub>eq</sub> = R₁ + R<sub>parallel</sub> = (R₁R₂ + R₁R₃ + R₂R₃)/(R₂ + R₃). Ohm’s law I = V/R<sub>eq</sub> gives the stated expression. No numerical resistor values are supplied.")),
]

def item(qid, question, answer, page, alternative=None, fig=None, altfig=None):
    graphic = '<figure><img src="diagrams/'+fig+'" alt="'+escape(fig.replace('-',' '))+'"><figcaption>Reconstructed explanatory diagram from the PDF’s text, not an image of the original paper.</figcaption></figure>' if fig else ''
    alternate = ''
    if alternative:
        aq, aa = alternative
        figure = '<figure><img src="diagrams/'+altfig+'" alt="'+escape(altfig.replace('-',' '))+'"><figcaption>Reconstructed explanatory diagram from the PDF’s text.</figcaption></figure>' if altfig else ''
        alternate = '<div class="option" id="'+qid+'-or"><div class="option-tag">OR alternative</div><p class="question">'+aq+'</p>'+figure+'<div class="answer"><strong>Worked answer</strong><p>'+aa+'</p>'+math_for(qid+'-or')+'</div></div>'
    return '<article class="paper-item" id="'+qid+'"><div class="item-head"><strong>'+qid.upper()+'</strong><span>PDF p. '+page+'</span></div><p class="question">'+question+'</p>'+graphic+'<div class="answer"><strong>Worked answer</strong><p>'+answer+'</p>'+math_for(qid)+'</div>'+alternate+'</article>'

q1 = ''.join(item('q1'+a,q,ans,p) for a,q,ans,p in Q1)
q2 = ''.join(item('q2'+a,q,ans,p) for a,q,ans,p in Q2)
q3 = ''.join(item('q3'+a,q,ans,p,alternative=alt,fig='wheatstone.svg' if a=='b' else None) for a,q,ans,p,alt in Q3)
q4 = ''.join(item('q4'+a,q,ans,p,alternative=alt,fig={'a':'shell-field.svg','c':'capacitor-network.svg'}.get(a),altfig='resistor-network.svg' if a=='c' else None) for a,q,ans,p,alt in Q4)

content = '''<div class="crumb"><a href="index.html">All subjects</a> / <a href="physics.html">Physics</a> / Paper &amp; answers</div><section class="subject-hero"><p class="eyebrow">Physics · supplied 2026 paper</p><h1>Question paper &amp;<br>worked answers</h1><p>50 marks · pass marks 17 · 2 hours · 8 pages. This is an unofficial transcription and solution guide to the PDF you supplied, not an official marking scheme.</p><p><a class="back" href="physics-paper-2026.pdf" download>Download the supplied PDF ↓</a></p></section>
<nav class="paper-jumps" aria-label="Question groups"><a href="#group1">1-mark MCQs</a><a href="#group2">2-mark short answers</a><a href="#group3">3-mark questions</a><a href="#group4">5-mark questions</a><a href="#analysis">Paper analysis</a></nav>
<aside class="note"><strong>Diagram note.</strong> The original PDF uses diagram placeholders and prose descriptions, not embedded circuit drawings. The diagrams below are reconstructed from that text so you can review and correct them. Where a stated mark split or wording looks unusual, the answer follows the actual PDF rather than the earlier OCR transcription.</aside>
<section class="paper-group" id="group1"><p class="eyebrow">Q1 · 1 × 6 = 6</p><h2>Multiple choice · answer all six</h2>'''+q1+'''</section>
<section class="paper-group" id="group2"><p class="eyebrow">Q2 · 2 × 8 = 16</p><h2>Short answers · choose any eight of nine</h2>'''+q2+'''</section>
<section class="paper-group" id="group3"><p class="eyebrow">Q3 · 3 × 6 = 18</p><h2>Six parts · choose one option per part</h2>'''+q3+'''</section>
<section class="paper-group" id="group4"><p class="eyebrow">Q4 · 5 × 2 = 10</p><h2>Choose any two of three</h2><p>Each part also has an OR option. The resistor network proof on PDF p. 8 is the OR for Q4(c), <strong>not</strong> a fifth question.</p>'''+q4+'''</section>
<section class="paper-group" id="analysis"><p class="eyebrow">After the exam</p><h2>Paper analysis</h2><div class="analysis-box"><p><strong>Structure:</strong> 6 + 16 + 18 + 10 = 50 marks. Q2 offers one question beyond the eight required; Q3 has six parts with internal OR choices; Q4 asks for two of three, with internal OR choices.</p><p><strong>Coverage:</strong> Electrostatics (charges, potential, Gauss), current electricity, magnetic effects and magnetism, and electromagnetic induction all appear. Q4(c) mixes circuit alternatives: a four-capacitor network or a resistor-network proof.</p><p><strong>Connection to preparation:</strong> The six-chapter Physics guide covers the concepts tested here. This paper particularly rewards short textbook definitions, unit recall, Gaussian-surface steps, magnetic-field derivations and Faraday/Lenz explanations. Without your actual answers or a question-by-question comparison to what you studied, we cannot honestly score the guide’s predictive accuracy or your performance.</p><p><strong>Skills tested:</strong> Direct definitions and units, symmetry-based derivations, circuit diagrams, numerical substitution and the energy explanation of Lenz’s law. This is a content analysis, not a grade or prediction of your score.</p><p><strong>Important distinctions:</strong> The capacitor network has four capacitors (not three); Q3(c)’s circular-coil calculation is its OR option; Q4(c)’s resistor network is an OR. The 250-turn flux question assumes the listed flux is per turn. Q3(c)’s coil calculation assumes one turn because no turn count is stated.</p><p><strong>What we cannot score:</strong> Your selected OR options and written responses haven’t been supplied. Do not treat this as an official mark scheme; an examiner may accept other correct wording or methods.</p></div></section><a class="back" href="physics.html">← Back to Physics</a>'''
(ROOT/'physics-paper-2026.html').write_text(layout('Physics paper and answers',content,'physics').replace('</head>','<link rel="stylesheet" href="physics/katex.min.css"><link rel="stylesheet" href="physics/katex-fonts.css"><link rel="stylesheet" href="paper.css"></head>',1),encoding='utf8')
print('paper built:',len(Q1),len(Q2),len(Q3),len(Q4),'question parts, with OR options')
